language: cpp
dist: xenial
notifications:
  email: false

cache:
  timeout: 600
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

# Define builds on mulitple OS/compiler combinations.
# Feel free to add/remove entries from this list.
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ubuntu-sdk-team-ppa
          packages:
            - lcov
            - g++-7
            - qtbase5-dev
            - qtdeclarative5-dev
            - libqt5webkit5-dev
            - libsqlite3-dev
            - qt5-default
            - qttools5-dev-tools
      env:
        - MATRIX_EVAL="CXX_COMPILER=g++-7; sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90"

    - os: osx
      osx_image: xcode10.1
      # addons:
      #   homebrew:
      #     packages:
      #     - lcov
      env:
        - MATRIX_EVAL="CXX_COMPILER=clang++"

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi

before_install:
  - eval "${MATRIX_EVAL}"
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew pin lcov; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install lcov; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; fi

install:
  - cd $PARENTDIR/build
  - cmake $PARENTDIR -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_CXX_COMPILER=$CXX_COMPILER
  - make

script:
  - make coverage

after_success:
  - cd $PARENTDIR/build
  - lcov --list coverage_out.info.cleaned # Show test report in travis log.
  - bash <(curl -s https://codecov.io/bash) -f coverage_out.info.cleaned || echo "Codecov did not collect coverage reports"
