general:
  name: "Emmerich Tending App"
  debug: true
devices:
  movement:
    sleep_pin: 16
    limit_switch_pin: 19
    x:
      step_pin: 20
      direction_pin: 21
      step_to_cm: 0.5
    y:
      step_pin: 6
      direction_pin: 26
      step_to_cm: 0.3
