general:
  name: "Emmerich Tending App"
  debug: true
finger:
  positioning:
    sleep_pin: 16
    x:
      step_pin: 20
      direction_pin: 21
      step_to_cm: 0.5
    y:
      step_pin: 6
      direction_pin: 26
      step_to_cm: 0.3
    limit_switch: 19
