general:
  name: "Emmerich Tending App"
  debug: true
devices:
  movement:
    sleep_pin: 16
    limit_switch_pin:
      home_x: 5
      home_y: 6
      edge: 11
      bin_detection: 14
    delay_each_step: 500
    speed: 10.0
    acceleration: 10.0
    x:
      step_pin: 26
      direction_pin: 13
      step_per_cm: 62.069
      step_per_mm: 6.2069
      reversed: true
    y:
      step_pin: 21
      direction_pin: 20
      step_per_cm: 62.069
      step_per_mm: 6.2069
      reversed: false
  watering:
    pump: 22
  rotation:
    motor: 12
    encoder: 0
  