general:
  name: "Emmerich Tending App"
  debug: true
devices:
  movement:
    sleep_pin: 16
    limit_switch_pin: 6
    delay_each_step: 500
    x:
      step_pin: 26
      direction_pin: 13
      step_per_cm: 62.069
      reversed: true
    y:
      step_pin: 21
      direction_pin: 20
      step_per_cm: 62.069
      reversed: false