set(FRUIT_USES_BOOST OFF)
set(BUILD_SHARED_LIBS ON)
#set(CMAKE_BUILD_TYPE Release)
#set(FRUIT_TESTS_USE_PRECOMPILED_HEADERS OFF)
#message(${CMAKE_BINARY_DIR})
add_subdirectory(${PROJECT_SOURCE_DIR}/external/fruit EXCLUDE_FROM_ALL)
#add_library(fruit INTERFACE)
target_include_directories(fruit INTERFACE ${PROJECT_SOURCE_DIR}/external/fruit/include)
target_include_directories(fruit INTERFACE ${CMAKE_BINARY_DIR}/external/fruit/include)
